### ISSUE TITLE
AGPL or MIT?

### ISSUE THREAD

**Issue by CocoaPriest** [giulio92/GLTableCollectionView#15]
In License file, there's MIT license. On the page you have the AGPL badge. So?...

**Comment by giulio92** [comment]
Hello @CocoaPriest,

The badges in the Readme section of the repository homepage are automatically generated by [Shields.io](http://shields.io/), so I think it's up to them to fix the licence recognition logic. GitHub on the other hand correctly recognise the MIT licence.

GLTableCollectionView follows MIT Licence starting from version [1.61-MIT](https://github.com/giulio92/GLTableCollectionView/releases/tag/1.61-MIT) and GPLv3 for versions before it
